# Generated by Django 5.1.6 on 2025-03-02 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shifoxona nomi')),
                ('district', models.CharField(choices=[('bektemir', 'Bektemir tumani'), ('chilonzor', 'Chilonzor tumani'), ('mirzo_ulugbek', 'Mirzo Ulugbek tumani'), ('mirobod', 'Mirobod tumani'), ('sergeli', 'Sergeli tumani'), ('shayxontohur', 'Shayxontohur tumani'), ('olmazor', 'Olmazor tumani'), ('uchtepa', 'Uchtepa tumani'), ('yakkasaroy', 'Yakkasaroy tumani'), ('yashnobod', 'Yashnobod tumani'), ('yunusobod', 'Yunusobod tumani')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospital_images/', verbose_name='Shifoxona rasmi')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Shifoxona raqami')),
                ('emergency_number', models.CharField(max_length=15, verbose_name='Tez yordam raqami')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Ishlash vaqtlari')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/', verbose_name='Shifokor rasmi')),
                ('doctor_type', models.CharField(choices=[('umumiy', 'Umumiy shifokor'), ('pediatr', 'Pediatr'), ('kardiolog', 'Kardiolog'), ('dermatolog', 'Dermatolog'), ('nevrolog', 'Nevrolog'), ('oftalmolog', 'Oftalmolog'), ('lor', 'Quloq, burun va tomoq shifokori (LOR)'), ('radiolog', 'Radiolog'), ('ortoped', 'Ortoped'), ('stomatolog', 'Stomatolog'), ('ichki_kasalliklar', 'Ichki kasalliklar boyicha mutaxassis'), ('urolog', 'Urolog'), ('ginekolog', 'Ginekolog'), ('onkolog', 'Onkolog'), ('shoshilinch', 'Shoshilinch tibbiy yordam shifokori'), ('yuqumli', 'Yuqumli kasalliklar boyicha mutaxassis'), ('fizioterapevt', 'Fizioterapevt'), ('dietolog', 'Dietolog'), ('psixolog', 'Psixolog')], max_length=50, verbose_name='Shifokor turi')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familyasi')),
                ('experience_years', models.IntegerField(verbose_name='Tajriba (yil)')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qabul narxi')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital', verbose_name='Shifoxona')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Bemor ismi')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Band qilinganmi')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Shifokor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital', verbose_name='Shifoxona')),
            ],
        ),
    ]
