# Generated by Django 5.1.6 on 2025-03-02 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_type',
            field=models.CharField(choices=[('umumiy', 'Umumiy shifokor'), ('pediatr', 'Pediatr'), ('kardiolog', 'Kardiolog'), ('dermatolog', 'Dermatolog'), ('nevrolog', 'Nevrolog'), ('oftalmolog', 'Oftalmolog'), ('lor', 'LOR'), ('radiolog', 'Radiolog'), ('ortoped', 'Ortoped'), ('stomatolog', 'Stomatolog'), ('ichki_kasalliklar', 'Ichki kasalliklar bo‘yicha mutaxassis'), ('urolog', 'Urolog'), ('ginekolog', 'Ginekolog'), ('onkolog', 'Onkolog'), ('shoshilinch', 'Shoshilinch tibbiy yordam shifokori'), ('yuqumli', 'Yuqumli kasalliklar bo‘yicha mutaxassis'), ('fizioterapevt', 'Fizioterapevt'), ('dietolog', 'Dietolog'), ('psixolog', 'Psixolog')], max_length=50, verbose_name='Shifokor turi'),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_available', models.BooleanField(default=True, verbose_name='Bo‘shmi')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Shifokor')),
            ],
        ),
    ]
